### ISSUE TITLE
[feature] proxy mode

### ISSUE THREAD

**Issue by r3t4k3r** [nymtech/nym-vpn-client#1052]
Now nymvpn works only like a all system vpn, which handle all system requests and send it over vpn tunnel. But i suggest to add ability to set up proxy mode in desktop client. 
For example it starts local proxy `http://127.0.0.1:2080` or `socks5://127.0.0.1:1080` etc...

It will helps some users to proxy only required applications using proxy settings inside the app.

Best wishes, r3tr4k3r.

**Comment by marcdbz** [comment]
Hi r3t4k3r, thanks for the feedback. This is a popular request and we have it identified on our backlog.
