### ISSUE TITLE
Admin privileged required

### ISSUE THREAD

**Issue by LukeWheeldon** [nymtech/nym-vpn-client#1069]
I am not able to use NymVPN because I am asked to provide administrator privileges, and my environment is very strict on not doing that. If the app would be on the App Store, it would not be a problem. I use other VPN apps that way.

<img width="283" alt="Screenshot 2024-09-06 at 10 48 12" src="https://github.com/user-attachments/assets/8ef2c579-dd7c-4fe7-88f1-eeddccb0d204">

**Comment by marcdbz** [comment]
Hello, thanks for reporting.

For NymVPN to function, this helper needs to be installed. Check https://support.nymvpn.com/hc/en-us/articles/28112201282577-Why-does-NymVPN-requests-to-install-a-helper-tool-on-macOS for more details.

The app will be made available on the Mac App Store once stabilized.

**Comment by LukeWheeldon** [comment]
Thank you for the clarification and looking forward to trying the Mac App store app.
