### ISSUE TITLE
App doesn't connect due to Failed exit policy check

### ISSUE THREAD

**Issue by I-I-IT** [nymtech/nym-vpn-client#1080]
One of the error message :

> 2024-09-07T14:53:48.000000788Z 18239 18324 WARNING libnymvpn: message= nym_vpn_lib::mixnet_processor: Received info response from the mixnet: destination failed exit policy filter check: 2.122.247.37:48298

It fails in 2hop/5hop modes. 
It says connected but no actual internet.

First I tried based settings (Germany), then I tries France entry node and Germany exit.

**Comment by marcdbz** [comment]
Thanks for reporting, our team will look into it

**Comment by octol** [comment]
When this happens, are you able to ping something like 1.1.1.1 or 8.8.8.8 in the terminal?

**Comment by rachyandco** [comment]
@I-I-IT is this still the case with the latest version?
