### ISSUE TITLE
Unknown error unhandled error: AuthenticatorAddressNotFound

### ISSUE THREAD

**Issue by eddieoz** [nymtech/nym-vpn-client#1098]
When trying to connect over 'Fast' from Estonia, it gives me an error "Unknown error unhandled error: AuthenticatorAddressNotFound"

When connecting through anonymous, it works well as intended.

`$ lsb_release -a`
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.3 LTS
Release:	22.04
Codename:	jammy

![image](https://github.com/user-attachments/assets/438bf0b6-c0ec-48ea-b504-63f65f8a5bdc)
[app.log](https://github.com/user-attachments/files/16942657/app.log)

**Comment by marcdbz** [comment]
Hi, thanks for reporting. Our team is on it.
