### ISSUE TITLE
[Solved] Verify flatpak listing on Flathub

### ISSUE THREAD

**Issue by RasheedAZ** [nymtech/nym-vpn-client#1341]
Thanks for packaging this app as flatpak and publishing on Flatpak.

Can you please verify the Flathub listing?

https://docs.flathub.org/docs/for-app-authors/verification

**Comment by rachyandco** [comment]
thanks for the tip. we will do it. (keeping issue open until done)

**Comment by rachyandco** [comment]
We are now verified https://flathub.org/apps/net.nymtech.NymVPN
