### ISSUE TITLE
failed to connect (unhandled exit): Task 'nym_vpn_lib-mixnet_client_main-gateway_transceiver-child' halted unexpectedly

### ISSUE THREAD

**Issue by bimih** [nymtech/nym-vpn-client#1357]
Connect for a few sec and then error: failed to connect (unhandled exit): Task 'nym_vpn_lib-mixnet_client_main-gateway_transceiver-child' halted unexpectedly

**Comment by rachyandco** [comment]
please state the version of the app and the OS and version of Os you are using

**Comment by bimih** [comment]
Hi,
MacOS Sequoia 15.0.1
NymVPN 1.2.1 (6)
Regards,

*Burim Hoti*

**Comment by rokas-ambrazevicius** [comment]
Hello,

we are aware of this issue and are actively working on a solution. It should be resolved in the next release. Thank you for submitting a report and for your patience and understanding!
