### ISSUE TITLE
[Solved] Blank window in *deb installation

### ISSUE THREAD

**Issue by 666xan666** [nymtech/nym-vpn-client#1442]
Hi, 
NymVPN Installed according manual on main page on Debian 12 testing, however when I start the program I got empty field in main window. It looks like this: 
![NymVPN](https://github.com/user-attachments/assets/7c95c34c-3226-45e6-a3ce-cec96c058d4e)

**Comment by doums** [comment]
Hi, is an nvidia gpu running on your system?

**Comment by 666xan666** [comment]
That solves the issue.
