### ISSUE TITLE
Add splitting settings

### ISSUE THREAD

**Issue by Korb** [nymtech/nym-vpn-client#1784]
_(since there is no mention of split tunneling in the README.md, nor in the Issues section, I assume that this function is missing in the application)_

I suggest considering the possibility of adding the ability to configure black and white lists of domains and applications. That is, to separate installed applications and internet-addresses into those for which a proxy is used, and those for which a proxy is not used.

This is useful for situations where certain applications or sites do not work correctly when using a proxy, or if there is a need to exclude the use of specific proxies for certain applications or sites.

**Comment by marcdbz** [comment]
Thanks for the suggestion, this is already a topic we have identified as part of our 2025 roadmap: https://trello.com/b/qVhBo3e2/nymvpn-public-roadmap

I will close the ticket, feel free to reopen it. Thanks.
