### ISSUE TITLE
Error after clicking connect

### ISSUE THREAD

**Issue by zerodartz** [nymtech/nym-vpn-client#230]
No matter the location i select or the mode I get this error after clicking connect: 
_Unable to open PF device file at '/dev/pf'_

Mac OS 14.4.1

Maybe i'm doing something wrong then let me know.

**Comment by rachyandco** [comment]
for now you must run the application in root. In the terminal, use `sudo` to launch the app.

**Comment by zerodartz** [comment]
thanks i did it - seems to work now.

for anyone else the exact command to use

`sudo /Applications/nym-vpn.app/Contents/MacOS/nym-vpn`
