### ISSUE TITLE
Unable to open PF device file at '/dev/pf'

### ISSUE THREAD

**Issue by ruloslll** [nymtech/nym-vpn-client#233]
<img width="397" alt="Снимок экрана 2024-03-28 в 14 38 24" src="https://github.com/nymtech/nym-vpn-client/assets/117834604/952c580b-3698-4add-b2ea-53f7aa68a3d1">

MacBook Air M1 16gb
macOS Sonoma 14.3.1

**Comment by rachyandco** [comment]
please make sure app is running in root mode, for now this is still needed.
in a terminal run `sudo` before calling nym-vpn

**Comment by ruloslll** [comment]
<img width="401" alt="Снимок экрана 2024-03-29 в 12 13 41" src="https://github.com/nymtech/nym-vpn-client/assets/117834604/40c21927-de8a-4b17-8d70-d065bfccacbb">
That's how it all works! Thank you!
Is the speed still low? or it seemed to me)

**Comment by rachyandco** [comment]
Great

Speed is still very low, lots of improvements are still to come. expect comparable speed with normal VPNs on the 2 hop mode. We also aim at a 10x speed improvement on the 5 hop.

**Comment by vlasinus** [comment]
> please make sure app is running in root mode, for now this is still needed. in a terminal run `sudo` before calling nym-vpn

You can get more detailed instructions on how to do this.
