### ISSUE TITLE
IPv6 Routing Error in VPN Logs

### ISSUE THREAD

**Issue by Gelois0** [nymtech/nym-vpn-client#235]
The logs show a recurring error where IPv6 traffic isn't routed to external destinations in the VPN client. The error message "Exit IPR not routing IPv6 traffic to external destinations" indicates a failure in routing IPv6 packets. This issue needs attention to ensure proper VPN functionality and network security.

![Kazam_screencast_00019](https://github.com/nymtech/nym-vpn-client/assets/115365052/5f1ef2f3-c620-4c48-9812-5d2a4c797aab)

**Comment by rachyandco** [comment]
The exit gateway doesn't appear to be setup to forward or route ipv6 traffic, or the host simply doesn't have ipv6 connectivity.

We are working on a "Directory Services"  that will allow the gateway to announces its enabled/disabled features.

This affects the client so possibly once "Directory Services" is place, the client will be able to filter out non-ipv6 exit gateways if it requires ipv6.

This is a key upcoming development to improve the  reliability of the vpn.
