### ISSUE TITLE
Still can not get it to work 

### ISSUE THREAD

**Issue by NiiiCOL3** [nymtech/nym-vpn-client#490]
failed to lookup gateways: failed to lookup described gateways: nym api request failed - there was an issue with the REST request: error sending request for url (https://validator.nymtech.net/api/v1/gateways/described)

**Comment by marcdbz** [comment]
Hello @NiiiCOL3, do you still experience this issue with the latest app builds? Otherwise we'll close this ticket. Thanks

**Comment by nfl0** [comment]
v1.0.7 still can't get to work!

**Comment by rachyandco** [comment]
> v1.0.7 still can't get to work!

can you get the logs and paste them here or https://support.nymvpn.com/hc/en-us/requests/new)

**Comment by marcdbz** [comment]
From https://github.com/nymtech/nym-vpn-client/issues/809 I see @NiiiCOL3 got it working. @nfl0 do you still experience connection issue with the latest apps? Thanks!

**Comment by marcdbz** [comment]
Hi @NiiiCOL3 do you still experience the issue? Thanks

**Comment by rachyandco** [comment]
closing as the latest versions solves the issue
