### ISSUE TITLE
tauri deb generated package not compatible with Ubuntu24

### ISSUE THREAD

**Issue by doums** [nymtech/nym-vpn-client#508]
upstream issue tauri-apps/tauri/issues/9662

### Possible workaround:

Add the following line to `/etc/apt/sources.list`

```
deb http://gb.archive.ubuntu.com/ubuntu jammy main
```

Then install `libwebkit2gtk-4.0-dev` package

```
sudo apt update
sudo apt install libwebkit2gtk-4.0-dev
```

**IMPORTANT**: it was recommended in this https://github.com/tauri-apps/tauri/issues/9662#issuecomment-2133959550 to undo the change to `sources.list` after installing to prevent problems with dependencies being deleted.

**Comment by octol** [comment]
Using `apt-get download --print-uris` it looks like the following is the least invasive way of installing the missing packages from 22.04 in 24.04. Tested it on a fresh VM and it seems to work
```
wget http://archive.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libwebkit2gtk-4.0-37_2.36.0-2ubuntu1_amd64.deb -P /tmp/nym
wget http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu70_70.1-2_amd64.deb -P /tmp/nym
wget http://archive.ubuntu.com/ubuntu/pool/main/w/webkit2gtk/libjavascriptcoregtk-4.0-18_2.36.0-2ubuntu1_amd64.deb -P /tmp/nym
sudo dpkg -i /tmp/nym/libwebkit2gtk-4.0-37_2.36.0-2ubuntu1_amd64.deb /tmp/nym/libicu70_70.1-2_amd64.deb /tmp/nym/libjavascriptcoregtk-4.0-18_2.36.0-2ubuntu1_amd64.deb
```

**Comment by doums** [comment]
resolved by https://github.com/nymtech/nym-vpn-client/pull/1096
