### ISSUE TITLE
Running nymvpn GUI app on windows entirely break windows 11

### ISSUE THREAD

**Issue by InterOhm** [nymtech/nym-vpn-client#779]
[0xv0c](https://github.com/0xv0c) commented [5 minutes ago] ( https://github.com/nymtech/nym-vpn-client/issues/778#issue-2433600376 ) ( my other account seem to be shadowbanned from github which prevent me from adding this issue ) 
I was forced to restore to a latest backup/restore point . Everytime i try to run / install nymvpn it entirely break my edge , video playback and render lots of stuff on my windows 11 OS unusable. Nym logs files doesn't show anything regarding this, I will dig .dmp ( since it break p much everything i ended up with 8gb of .dmp from widget , edge , webview and others apps ). I will try to look @ event viewer and attempt to debug it when i have time.

---- i was able to reproduce on an fresh install on another partitions with minimal hardening and debloating. ( I had to ensure it wasn't my  current setup  or settings)

**Comment by marcdbz** [comment]
Thanks for reporting. Could you share more details about the issue? I couldn't access the linked comment you posted. We have several team members running NymVPN on Windows 11, incl. on Parallels Desktop, with no issues so far. Thanks!

**Comment by InterOhm** [comment]
Unfortunately i was not aware than after using my token once if i reformat or reinstall stuff the token wouldn't work anymore. I'm currently using it on my linux operating system. As soon i have time to mess around with that windows 11 , gather logs, data and .dmp  i will provide them. I also need to figure out if those can be regen or I have to get new one.

**Comment by marcdbz** [comment]
Thanks. In case you need new credentials, you can get in touch with our support at https://support.nymvpn.com/hc/en-us/requests/new

**Comment by rachyandco** [comment]
issue is pretty old, and there are newer version of the windows app.

https://nymvpn.com/en/download/windows the latest version is 0.2.3 that you can try. the issue is probably fixed.
