### ISSUE TITLE
Finally

### ISSUE THREAD

**Issue by NiiiCOL3** [nymtech/nym-vpn-client#809]
After numerous attempts for several months, this most recent version and most recent credential I received via email worked like a charm and I was able to finally connect NymVPN successfully without encountering any errors unlike what I have been experiencing before. Kudos Nymtech. Job well done.

![image](https://github.com/user-attachments/assets/6e6d6a71-2600-4cdd-8c24-67002a935708)

Regards;
Nicol3

**Comment by marcdbz** [comment]
Thanks for reporting this, glad it works now! From the screenshot, it looks like you may not have the latest app version. Make sure to check https://nymvpn.com/en/download/ to get the latest stable app. Thanks!

**Comment by NiiiCOL3** [comment]
> Thanks for reporting this, glad it works now! From the screenshot, it looks like you may not have the latest app version. Make sure to check https://nymvpn.com/en/download/ to get the latest stable app. Thanks!

Sorry for the very late response and yeah I have updated it to the most recent version and it's working good to date. Good job to Nym :) Proud Nymster :)
