### ISSUE TITLE
Censorship in Russian and Indian servers

### ISSUE THREAD

**Issue by redpay** [nymtech/nym-vpn-client#824]
When I use Russia as my exit node politically sensitive websites like Facebook and Voice of America do not load, I suspect they are being blocked, and when using the Indian exit nodes it is websites like Pornhub and XVideos that do not load, You get no warning of the website being blocked only that the connection can´t be established. Perhaps there should be a warning about this somewhere in the FAQ? And if they are blocking websites in that datacentre what else are doing, are they monitoring too? They must have a way to see the websites I visit to decide what they block and what not.

**Comment by marcdbz** [comment]
Thanks for reporting, let me share with the team and come back to you.

**Comment by marcdbz** [comment]
Hello redpay,

We've added the following article to our FAQ: https://support.nymvpn.com/hc/en-us/articles/28133009717009-Why-do-online-activities-get-censored-when-choosing-certain-exit-locations Happy to hear your thoughts.

Thanks.
