### ISSUE TITLE
NYMvpn not available in f-droid

### ISSUE THREAD

**Issue by Xcertik-Realist** [nymtech/nym-vpn-client#914]
as it says above the android client isn't available in F-DROID like stated please fix

**Comment by rachyandco** [comment]
Currently you can add nym repository in F-droid by following these instructions: https://github.com/nymtech/fdroid



1. In the F-droid app, navigate to Settings > Repositories and click the "+" floating action button.
2. To add the repository, click "SCAN QR CODE" and scan the QR code below or add the repository manually with the following URL:

`https://raw.githubusercontent.com/nymtech/fdroid/main/fdroid/repo?fingerprint=06C095C54BBFE147C986FD29ADF4E9BCD5E95ECACD6D865C6045B66B0B5500FB`

F-Droid repo QR code 

![qrcode](https://github.com/user-attachments/assets/163e2869-c5cb-4b22-9672-4e59529211e1)


Once the stable version will be be released, we will push the app to the main F-droid repo. We will keep this issue open until then.
