### ISSUE TITLE
Windows app error on opening everytime !!!

### ISSUE THREAD

**Issue by Xcertik-Realist** [nymtech/nym-vpn-client#915]
Failed to lookup gateway

no entry gateway available for location BR, available countries: 

get this error everytime tried all listed fixes nothing works and have burnt my alpha code trying to test your mixnet !!!!

All was fine first time i used it and when pc rebbooted now getting this errors and can not fix

**Comment by Xcertik-Realist** [comment]
is it possible to move your creds to another machine ??

**Comment by marcdbz** [comment]
Hello,

You can use the credentials on multiple devices. If you need a new credential, you can reach out to our Support team using https://support.nymvpn.com/hc/en-us/requests/new

Thanks
