### ISSUE TITLE
Windows 11 Pro error

### ISSUE THREAD

**Issue by TheSaltyJ** [nymtech/nym-vpn-client#964]
Installed the windows app (v.0.1.8) and added my credentials. Upon connection, I get the following error: 

Unknown error

unhandled error: SDKError( ClientCoreError( IoError( Os { code: 32, kind: Uncategorized, message: "The process cannot access the file because it is being used by another process.", }, ), ), )

**Comment by marcdbz** [comment]
Thanks for reporting. This is a known issue. We'll come back to you once addressed.

**Comment by rachyandco** [comment]
Windows is now on 0.2.3 https://nymvpn.com/en/download/windows

**Comment by TheSaltyJ** [comment]
Issue persists on 0.2.3
